{{- if .Values.polytomic.cache.enabled -}}
{{ if eq .Values.polytomic.cache.storage_class "efs-sc" }}
{{ if eq .Values.polytomic.cache.type "static" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.polytomic.cache.volume_name }}
spec:
  capacity:
    storage: {{ .Values.polytomic.cache.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.polytomic.cache.efs_id }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.polytomic.cache.volume_name }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.polytomic.cache.size }}
{{- else }}
{{- end }}
{{- else }}
{{- end -}}
{{- if index .Values "nfs-server-provisioner" "enabled" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.polytomic.cache.volume_name }}
spec:
  storageClassName: {{ index .Values "nfs-server-provisioner" "storageClass" "name" }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.polytomic.cache.size }}
{{- else }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.polytomic.cache.volume_name }}
spec:
  storageClassName: {{ .Values.polytomic.cache.storage_class }}
  capacity:
    storage: {{ .Values.polytomic.cache.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: {{ .Values.polytomic.cache.csi_driver }}
    volumeHandle: {{ .Values.polytomic.cache.volume_handle }}
    {{- if .Values.polytomic.cache.volume_attributes }}
    volumeAttributes:
    {{- range $key, $value := .Values.polytomic.cache.volume_attributes }}
      {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.polytomic.cache.volume_name }}
spec:
  storageClassName: {{ .Values.polytomic.cache.storage_class }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.polytomic.cache.size }}
{{- end -}}
{{- end -}}