apiVersion: v1
kind: Service
metadata:
  name: {{ include "polytomic.fullname" . }}
  labels:
    {{- include "polytomic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- if not .Values.development -}}
    {{- include "polytomic.web-selectorLabels" . | nindent 4 }}
    {{- else -}}
    {{- include "polytomic.dev-selectorLabels" . | nindent 4 }}
    {{- end }}
