{{- if not .Values.development -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polytomic.fullname" . }}-sync
  labels:
    {{- include "polytomic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.sync.autoscaling.enabled }}
  replicas: {{ .Values.sync.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "polytomic.sync-selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sync.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "polytomic.sync-selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "polytomic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.sync.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.sync.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              {{- else }}
              name: {{ include "polytomic.fullname" . }}-config
              {{- end }}
          env:          
          - name: ROLE
            value: sync
          volumeMounts:
          - mountPath: /var/polytomic
            name: cache-volume
            {{ if .Values.polytomic.cache.sub_path }}
            subPath: {{ .Values.polytomic.cache.sub_path }}
            {{- end }}
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
      {{- if .Values.sync.sidecarContainers }}
      {{- toYaml .Values.sync.sidecarContainers | nindent 8 }}
      {{- end }}
      {{- with .Values.sync.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sync.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{ if and (index .Values "nfs-server-provisioner" "enabled") (.Values.polytomic.cache.enabled) }}
      - name: cache-volume
        persistentVolumeClaim:
          claimName: {{ .Values.polytomic.cache.volume_name }}
      {{ else }}
      - name: cache-volume
        emptyDir: {}
      {{- end -}}
{{- end }}