{{- if .Values.polytomic.vector.daemonset.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "polytomic.fullname" . }}-vector
  labels:
    {{- include "polytomic.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
  {{- $serviceAccount := .Values.polytomic.vector.daemonset.serviceAccount }}
  {{- if or $serviceAccount.roleArn $serviceAccount.annotations }}
  annotations:
    {{- with $serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
