formatter: "" # this is required

version: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Polytomic On ECS Fargate

  This module will all the necessary configuration to run a Polytomic On ECS Fargate.
  Using the architecture outlined in the image below.

  ## Usage

  To run this example you need to execute:

  ```bash
  $ terraform init
  $ terraform plan
  $ terraform apply
  ```

  # Architecture
  ![arch](./aws_arch.png)

  # Examples

  Complete
  ```hcl
  {{ include "../../examples/ecs-complete/main.tf" }}
  ```


  Minimal
  ```hcl
  {{ include "../../examples/ecs-minimal/main.tf" }}
  ```
  
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true