[sources.in]
type = "splunk_hec"
address = "0.0.0.0:8000"
token = "test"
valid_tokens = [ "test" ]

[transforms.parse]
type = "remap"
inputs = [ "in" ]
source = ". |= object!(parse_json!(.message))"

[transforms.filter]
type = "filter"
inputs = [ "parse" ]
condition = 'exists(.execution_id) && exists(.organization_id) && exists(.sync_id)'

[sinks.s3]
type = "aws_s3"
inputs = [ "filter" ]
bucket =  "${EXECUTION_LOG_BUCKET:?err}"
key_prefix = "{{ organization_id  }}/execution_logs/{{ sync_id }}/{{ execution_id }}"
region = "${AWS_REGION:?err}"
filename_append_uuid = false
filename_time_format = ""
filename_extension = "json"
[sinks.s3.encoding]
codec = "json"
[sinks.s3.batch]
timeout_secs = 10


[sinks.debug]
type = "console"
inputs = [ "in" ]
target = "stdout"
[sinks.debug.encoding]
codec = "json"