name: trivy-terraform-scan
on:
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    name: Trivy Terraform scan
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: config
          scan-ref: terraform
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL
          exit-code: '1'
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
